name='rrpam-wds'
version='0.1.0'
license='GPLV3'
description='Risk-based renewal planning for asset management of water distribution systems'
author='Assela Pathirana'
author_email='assela@pathirana.net'
url='https://github.com/asselapathirana/RRPam-WDS'